language: objective-c
osx_image: xcode7.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    include:
      - os: osx
        language: objective-c
        osx_image: xcode9
	script:
          - set -o pipefail
          - xcodebuild -version

