env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
  language: objective-c
  osx_image: xcode9
  language: generic
  osx_image: xcode9
  script:
    - swift test

  notifications:
    email: false
